### ISSUE TITLE
import to android studio: cannot load module file (missing iml files)

### ISSUE THREAD

**Issue by nikonakoneko** [combluotion/Volley1#1]
![mssiml](https://user-images.githubusercontent.com/16183/32882139-a90a8c12-cab3-11e7-9e65-e4f36597c31c.png)

seems to be a known issue
see
* https://stackoverflow.com/questions/36446959/android-studio-and-github-missing-iml-files
* https://stackoverflow.com/questions/35476331/git-dont-able-to-upload-iml-filefrom-android-studio
* https://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project

should be just a gitignore thing

**Comment by combluotion** [comment]
hola papi lo se pero como hago ahora ya esta aqui metido

**Comment by combluotion** [comment]
lo solucionastes?

**Comment by nikonakoneko** [comment]
bueno es raro.. po nada #wontfix
